// Builds the upload bundles:
//   release/hoshidub-website-static.zip  shared hosting (Hostinger "Custom PHP/HTML website", cPanel...):
//                                        the built site plus .htaccess; unzip into public_html
//   release/hoshidub-website-node.zip    Node hosting / VPS: dist + server.js + slim package.json
//   npm run package
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { securityHeaders } from '../security.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const release = path.join(root, 'release');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

execFileSync(process.execPath, [path.join(root, 'node_modules', 'astro', 'bin', 'astro.mjs'), 'build'], { cwd: root, stdio: 'inherit' });
fs.rmSync(release, { recursive: true, force: true });

// Windows tar (bsdtar) writes zip files; GNU tar from Git can't
function zipDir(dir, zip) {
  // list the top-level entries by name so paths inside the zip don't start with "./" (some hosting importers choke on it)
  if (process.platform === 'win32') execFileSync(path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'tar.exe'), ['-a', '-cf', zip, '-C', dir, ...fs.readdirSync(dir)], { stdio: 'inherit' });
  else execFileSync('zip', ['-qr', zip, '.'], { cwd: dir, stdio: 'inherit' });
  console.log(`${path.basename(zip)}  ${(fs.statSync(zip).size / 1e6).toFixed(1)} MB`);
}

// ---- static bundle (Apache / LiteSpeed) ----
const quote = (v) => `"${v.replace(/"/g, '\\"')}"`;
const htaccess = `# Hoshidub website (generated by tools/package.mjs)
Options -Indexes -MultiViews
DirectoryIndex index.html
ErrorDocument 404 /404.html

AddType model/gltf-binary .glb
AddType video/webm .webm
AddType video/mp4 .mp4
AddType font/woff2 .woff2
AddType image/webp .webp

<IfModule mod_rewrite.c>
  RewriteEngine On
  # always HTTPS
  RewriteCond %{HTTPS} off
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  # old-style /about.html links go to /about
  RewriteCond %{THE_REQUEST} \\s/([^.?\\s]+)\\.html[\\s?]
  RewriteRule ^ /%1 [R=301,L]
  # clean links: /about serves about.html
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME}.html -f
  RewriteRule ^(.+?)/?$ $1.html [L]
</IfModule>

<IfModule mod_headers.c>
${Object.entries(securityHeaders).map(([k, v]) => `  Header always set ${k} ${quote(v)}`).join('\n')}
  Header unset X-Powered-By
  # pages revalidate; images, fonts, video and the model cache for a week
  <FilesMatch "\\.(html|xml|txt)$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>
  <FilesMatch "\\.(webp|png|jpg|svg|woff2|glb|mp4|webm)$">
    Header set Cache-Control "public, max-age=604800"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml application/xml application/javascript text/javascript image/svg+xml model/gltf-binary
</IfModule>
`;
// hashed build files never change: cache them for a year
const immutable = `<IfModule mod_headers.c>
  Header set Cache-Control "public, max-age=31536000, immutable"
</IfModule>
`;
const stat = path.join(release, 'static');
fs.cpSync(path.join(root, 'dist'), stat, { recursive: true });
fs.writeFileSync(path.join(stat, '.htaccess'), htaccess);
fs.writeFileSync(path.join(stat, '_astro', '.htaccess'), immutable);
zipDir(stat, path.join(release, 'hoshidub-website-static.zip'));

// ---- Node bundle ----
const node = path.join(release, 'node');
fs.mkdirSync(node, { recursive: true });
fs.cpSync(path.join(root, 'dist'), path.join(node, 'dist'), { recursive: true });
for (const f of ['server.js', 'security.js']) fs.copyFileSync(path.join(root, f), path.join(node, f));
fs.writeFileSync(path.join(node, 'package.json'), JSON.stringify({
  name: pkg.name, version: pkg.version, private: true, type: 'module', description: pkg.description,
  scripts: { start: 'node server.js' },
  engines: pkg.engines,
  dependencies: { compression: pkg.dependencies.compression, express: pkg.dependencies.express },
}, null, 2) + '\n');
fs.writeFileSync(path.join(node, 'README.txt'), [
  'Hoshidub website - Node bundle',
  '',
  '1. Upload everything in this folder to your server.',
  '2. In that folder run:   npm install --omit=dev',
  '3. Start it:             npm start        (listens on $PORT, default 3000)',
  '',
  'Keep it running with your host\'s Node app manager, or pm2:',
  '   npm install -g pm2 && pm2 start server.js --name hoshidub && pm2 save',
  '',
].join('\n'));
zipDir(node, path.join(release, 'hoshidub-website-node.zip'));
